// Package storage contains compatibility aliases for the artifact content
// storage port.
//
// The port is owned by the artifact application layer. Infrastructure storage
// backends import this package for historical compatibility while implementing
// the application-owned contract.
package storage

import appartifact "github.com/AFDEAPAC/kish/internal/application/artifact"

// ErrObjectNotFound is returned when the requested storage key does not exist.
var ErrObjectNotFound = appartifact.ErrObjectNotFound

// ErrInsufficientStorage is returned when a backend cannot accept new object
// content because disk space, bucket quota, or a provider free-space threshold
// has been reached.
var ErrInsufficientStorage = appartifact.ErrInsufficientStorage

// ObjectInfo describes a stored object without reading its content.
type ObjectInfo = appartifact.ObjectInfo

// ObjectStore is the interface that storage backends must implement.
//
// Keys are opaque slash-separated strings generated by the application layer
// (e.g. "testcases/{case_id}/artifacts/{artifact_name}"). Implementations must
// not interpret key structure beyond using it as a path identifier.
type ObjectStore = appartifact.ObjectStore
