// Package storage defines the ObjectStore abstraction for artifact content.
//
// The ObjectStore interface decouples the artifact application layer from any
// specific storage backend. The first implementation is a local filesystem store.
// Future backends (S3-compatible) can be added without changing domain or HTTP code.
package storage

import (
	"context"
	"errors"
	"io"
	"time"
)

// ErrObjectNotFound is returned when the requested storage key does not exist.
var ErrObjectNotFound = errors.New("object not found")

// ErrInsufficientStorage is returned when a backend cannot accept new object
// content because disk space, bucket quota, or a provider free-space threshold
// has been reached.
var ErrInsufficientStorage = errors.New("insufficient storage")

// ObjectInfo describes a stored object without reading its content.
type ObjectInfo struct {
	Key         string
	Size        int64
	ContentType string
	UpdatedAt   time.Time
}

// ObjectStore is the interface that storage backends must implement.
//
// Keys are opaque slash-separated strings generated by the application layer
// (e.g. "testcases/{case_id}/artifacts/{artifact_name}"). Implementations must
// not interpret key structure beyond using it as a path identifier.
type ObjectStore interface {
	// PutObject writes r to the store under key. size is the expected byte count
	// of r; passing -1 means unknown (implementations may buffer or reject).
	// If an object already exists at key it is replaced atomically.
	PutObject(ctx context.Context, key string, r io.Reader, size int64, contentType string) error

	// GetObject retrieves the object at key. The caller is responsible for
	// closing the returned ReadCloser. Returns ErrObjectNotFound if absent.
	GetObject(ctx context.Context, key string) (io.ReadCloser, ObjectInfo, error)

	// DeleteObject removes the object at key. If the key does not exist the
	// implementation must return nil (idempotent delete).
	DeleteObject(ctx context.Context, key string) error
}
