package artifact

import (
	"context"
	"errors"
	"io"
	"time"
)

// ErrObjectNotFound is returned by ObjectStore implementations when artifact
// content cannot be found for a metadata record.
var ErrObjectNotFound = errors.New("object not found")

// ErrInsufficientStorage reports that an ObjectStore backend cannot accept new
// content because local or remote storage capacity has been exhausted.
var ErrInsufficientStorage = errors.New("insufficient storage")

// ObjectInfo describes stored artifact content without requiring callers to
// open the content stream.
type ObjectInfo struct {
	Key         string
	Size        int64
	ContentType string
	UpdatedAt   time.Time
}

// ObjectStore is the artifact use case's content storage port.
//
// Implementations live in outer infrastructure packages. Keys are generated by
// the application layer and must be treated as opaque identifiers by storage
// backends.
type ObjectStore interface {
	PutObject(ctx context.Context, key string, r io.Reader, size int64, contentType string) error
	GetObject(ctx context.Context, key string) (io.ReadCloser, ObjectInfo, error)
	DeleteObject(ctx context.Context, key string) error
}
