// Package local implements ObjectStore backed by the local filesystem.
//
// Objects are stored under a configured root directory. Storage keys are
// slash-separated paths generated by the application layer; they are converted
// to OS-native paths and validated to prevent directory traversal.
//
// Writes are atomic: content is written to a sibling .tmp file and then
// renamed into the final location. This prevents partial reads on concurrent
// access and avoids leaving corrupt files after a crash.
package local

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/AFDEAPAC/kish/internal/infrastructure/storage"
)

// Store is a local filesystem implementation of storage.ObjectStore.
type Store struct {
	// root is the absolute path to the storage root directory.
	root string
}

// New constructs a Store rooted at root.
// root is created lazily on the first PutObject call.
func New(root string) (*Store, error) {
	abs, err := filepath.Abs(root)
	if err != nil {
		return nil, fmt.Errorf("local store: resolve root %q: %w", root, err)
	}
	return &Store{root: abs}, nil
}

// PutObject writes r to the store under key, replacing any existing content.
// The file is written atomically via a temporary file and rename.
func (s *Store) PutObject(_ context.Context, key string, r io.Reader, _ int64, _ string) error {
	dest, err := s.safeJoin(key)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(dest), 0755); err != nil {
		return fmt.Errorf("local store: mkdir for %q: %w", key, err)
	}

	// Write to a sibling temp file so the rename is atomic on the same filesystem.
	tmp, err := os.CreateTemp(filepath.Dir(dest), ".kish-upload-*.tmp")
	if err != nil {
		return fmt.Errorf("local store: create temp for %q: %w", key, err)
	}
	tmpPath := tmp.Name()

	// Always clean up the temp file on failure.
	committed := false
	defer func() {
		if !committed {
			_ = os.Remove(tmpPath)
		}
	}()

	if _, err := io.Copy(tmp, r); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("local store: write %q: %w", key, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("local store: close temp %q: %w", key, err)
	}

	if err := os.Rename(tmpPath, dest); err != nil {
		return fmt.Errorf("local store: rename to %q: %w", key, err)
	}
	committed = true
	return nil
}

// GetObject returns a ReadCloser for the object at key.
// Returns storage.ErrObjectNotFound if the key does not exist.
func (s *Store) GetObject(_ context.Context, key string) (io.ReadCloser, storage.ObjectInfo, error) {
	path, err := s.safeJoin(key)
	if err != nil {
		return nil, storage.ObjectInfo{}, err
	}

	info, err := os.Stat(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, storage.ObjectInfo{}, storage.ErrObjectNotFound
		}
		return nil, storage.ObjectInfo{}, fmt.Errorf("local store: stat %q: %w", key, err)
	}

	f, err := os.Open(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, storage.ObjectInfo{}, storage.ErrObjectNotFound
		}
		return nil, storage.ObjectInfo{}, fmt.Errorf("local store: open %q: %w", key, err)
	}

	return f, storage.ObjectInfo{
		Key:       key,
		Size:      info.Size(),
		UpdatedAt: info.ModTime().UTC(),
	}, nil
}

// DeleteObject removes the object at key. If the key does not exist, nil is returned.
func (s *Store) DeleteObject(_ context.Context, key string) error {
	path, err := s.safeJoin(key)
	if err != nil {
		return err
	}

	if err := os.Remove(path); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return fmt.Errorf("local store: delete %q: %w", key, err)
	}
	return nil
}

// safeJoin converts a slash-separated storage key into an absolute filesystem
// path under root and rejects keys that would escape the root directory.
//
// The key must use only forward slashes. Any path traversal attempt
// (e.g. "../../../etc/passwd") is rejected with an error.
func (s *Store) safeJoin(key string) (string, error) {
	// Convert the slash-separated key to an OS-native relative path.
	rel := filepath.FromSlash(key)

	// filepath.Join cleans the result, resolving ".." segments.
	joined := filepath.Join(s.root, rel)

	// Verify the cleaned path is still under root.
	// The trailing separator ensures "root" itself is not accepted as a key.
	rootWithSep := s.root + string(os.PathSeparator)
	if joined != s.root && !strings.HasPrefix(joined, rootWithSep) {
		return "", fmt.Errorf("local store: key %q escapes storage root", key)
	}
	if joined == s.root {
		return "", fmt.Errorf("local store: key %q resolves to storage root itself", key)
	}

	return joined, nil
}

// Root returns the absolute root directory used by this store.
// Intended for use in tests and logging only.
func (s *Store) Root() string { return s.root }

// ContentTypeFromFile is a best-effort content-type helper.
// The local store does not persist content-type; this function is provided for
// callers that want to attach content-type to ObjectInfo from file metadata.
func ContentTypeFromFile(path string) string {
	switch strings.ToLower(filepath.Ext(path)) {
	case ".json":
		return "application/json"
	case ".txt", ".log":
		return "text/plain"
	case ".sh":
		return "text/x-shellscript"
	case ".yaml", ".yml":
		return "application/yaml"
	default:
		return "application/octet-stream"
	}
}

// statUpdatedAt is a helper used in tests to inspect file mtime.
func statUpdatedAt(path string) (time.Time, error) {
	info, err := os.Stat(path)
	if err != nil {
		return time.Time{}, err
	}
	return info.ModTime().UTC(), nil
}
